# Generated by Django 4.2.7 on 2023-12-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_teammember_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
